### ISSUE TITLE
KeyError: 'tls' with 0.2.1

### ISSUE THREAD

**Issue by dayer4b** [6si/shipwright#14]
Using the latest version of shipwright (0.2.1), when I run shipwright on a project (with a .shipwright.json file), I get an error about `tls`.  

This didn't happen with the previous version I was using (which was pip installed from a pre-release commit using `sudo pip install git+git://github.com/6si/shipwright.git@b076b5116e77d84957c3d0dd318b48c7c9d42cf7`).

```bash
~$ shipwright
Traceback (most recent call last):
  File "/usr/local/bin/shipwright", line 9, in <module>
    load_entry_point('shipwright==0.2.1', 'console_scripts', 'shipwright')()
  File "/usr/local/lib/python2.7/dist-packages/shipwright/cli.py", line 157, in main
    client_cfg['tls'].assert_hostname = assert_hostname
KeyError: 'tls'
```

From what I've gathered by Googling, this has something to do with docker.py and the usage of some Docker environment variables.  However, if I'm running docker locally on a Unix socket, I shouldn't need to worry about `DOCKER_CERT_PATH`, `DOCKER_HOST`, and `DOCKER_TLS_VERIFY`, right?

Can Shipwright relax this TLS information requirement if I'm running docker on a socket?

**Comment by srobertson** [comment]
Let me know if that works for you. Just pushed 0.2.2 to pypi as well.

**Comment by dayer4b** [comment]
Yes!  that worked.  Thanks!

On Tue, Jan 6, 2015 at 1:03 PM, Scott Robertson <notifications@github.com>
wrote:

> Let me know if that works for you. Just pushed 0.2.2 to pypi as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/6si/shipwright/issues/14#issuecomment-68914423>.
>



-- 
Sunil
