### ISSUE TITLE
BUG Shipwright 0.2.1 KeyError : 'tls'

### ISSUE THREAD

**Issue by tangicolin** [6si/shipwright#15]
Lastest shipwright version install from pip bug with the following error:

     File "/usr/local/bin/shipwright", line 9, in <module>
    load_entry_point('shipwright==0.2.1', 'console_scripts', 'shipwright')() 
    File "/usr/local/lib/python2.7/dist-packages/shipwright/cli.py", line 157, in main 
    client_cfg['tls'].assert_hostname = assert_hostname  
    KeyError: 'tls'

**Comment by srobertson** [comment]
Latest version 0.2.2 has this fixed. Try pip install -U shipwright>=0.2.2
