### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by graingert** [6si/shipwright#23]
It would be great to support Python 3

**Comment by srobertson** [comment]
PRs welcome! :)

**Comment by graingert** [comment]
@srobertson I've made PRs to your deps:

see:
codd: https://github.com/trivio/codd/pull/3
xlocal: https://bitbucket.org/hpk42/xlocal/pull-requests/
zipper: https://github.com/trivio/zipper/pull/2

**Comment by srobertson** [comment]
Wow, thanks for all the hard work on this! Soon as I get a moment I'll check this out and try it under python 3

**Comment by graingert** [comment]
@srobertson any updates on this?

**Comment by srobertson** [comment]
Merged your excellent set of PRs
