### ISSUE TITLE
run unit tests on Travis via tox

### ISSUE THREAD

**Issue by graingert** [6si/shipwright#26]

**Comment by graingert** [comment]
it's difficult to find out what's broken when doing a Python 3 port etc.

**Comment by srobertson** [comment]
Shipwright uses doctests. Something like `nose --with-doctest` should do the trick.

**Comment by graingert** [comment]
@srobertson https://github.com/6si/shipwright/pull/28/files sadly 7 of the tests are broken

**Comment by srobertson** [comment]
:( looking into it. Thanks for all the hard work to get it to this point.

**Comment by srobertson** [comment]
Fixed in #36
