### ISSUE TITLE
shipwright sometimes doesn't push the "latest" tag

### ISSUE THREAD

**Issue by graingert** [6si/shipwright#34]
actually it seems that shipwright never pushed the "latest" tag

**Comment by nigelgbanks** [comment]
I'm experiencing this as well.

**Comment by nigelgbanks** [comment]
For me at least it seems it's due to the structure of the code, and failing builds. Images will only be tagged **latest**, if **all** builds succeed rather than immediately after the single image has been built, when it's tagged with git-commit hash. Same goes for **branch** names.

**Comment by nigelgbanks** [comment]
My previous comment actually had to do with a separate issue, which may or may not be by design.
