### ISSUE TITLE
shipwright won't build dependant images if the image:latest doesn't already exist on docker hub

### ISSUE THREAD

**Issue by nigelgbanks** [6si/shipwright#38]
Hello first of all great tool! I'm happy to replace my home-grown bash script. 

I have a number of images in a single git repository, shipwright builds though all of them right until it reaches one that doesn't have a hub.docker repository, at which point it refuses to continue even though it has already built this dependency (In the example below it's _docker-compose_ image). 

Even if you create a repository on hub.docker, but don't push an image, it will refuse to build dependant images, creating a bit of a bootstrapping problem, if you want to use shipwright from the very beginning. 
 
```
Tagging nigelgbanks/base:eab68eb97bf5 to nigelgbanks/base:eab68eb97bf5
Tagging nigelgbanks/python:eab68eb97bf5 to nigelgbanks/python:eab68eb97bf5
Tagging nigelgbanks/ruby:eab68eb97bf5 to nigelgbanks/ruby:eab68eb97bf5
Tagging nigelgbanks/awscli:eab68eb97bf5 to nigelgbanks/awscli:eab68eb97bf5
Tagging nigelgbanks/docker-compose:eab68eb97bf5 to nigelgbanks/docker-compose:eab68eb97bf5
Tagging nigelgbanks/shipwright:eab68eb97bf5 to nigelgbanks/shipwright:eab68eb97bf5
Tagging nigelgbanks/tugboat:eab68eb97bf5 to nigelgbanks/tugboat:eab68eb97bf5
nigelgbanks/ansible | Step 1 : FROM nigelgbanks/docker-compose
nigelgbanks/ansible | [STATUS] : Pulling repository docker.io/nigelgbanks/docker-compose
nigelgbanks/ansible | [ERROR] Error: Status 503 trying to pull repository nigelgbanks/docker-compose: "<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n\n"
```

**Comment by nigelgbanks** [comment]
Ah perhaps Docker Hub is to blame they are having technical difficulties at the moment.

**Comment by srobertson** [comment]
Correct... shipwright eventually needs a base image loaded into docker for all the derived images to be built off.  But it relies on docker to take care of all that. So if you don't have the base image loaded in your docker daemon or docke-hub is down there's nothing it can do.

**Comment by nigelgbanks** [comment]
Ah I so it's using the **latest** tag to build all dependant images (of course), so my issues is that it doesn't actually set the images it has previously built to have the **latest** tag. So it doesn't find the appropriate image for building the dependant image although it has already been built and tagged with the commit and the branch as tags.

**Comment by nigelgbanks** [comment]
Hmm no it doesn't seem to be the case when building, It uses the appropriate images that it has just built:

```
nigelgbanks/base | Step 1 : FROM quay.io/justcontainers/base-alpine
...
nigelgbanks/python | Step 1 : FROM nigelgbanks/base:eab68eb97bf5
...
nigelgbanks/docker-compose | Step 1 : FROM nigelgbanks/python:eab68eb97bf5
```

Except when it gets to my **nigelgbanks/ansible** image:

```
nigelgbanks/ansible | Step 1 : FROM nigelgbanks/docker-compose
```

It tries to pull **nigelgbanks/docker-compose** despite having just built it locally.

**Comment by nigelgbanks** [comment]
Found out the actual problem was related to a regex, and now it's documented in issue #40
