### ISSUE TITLE
Building without having to commit to git (for dev)

### ISSUE THREAD

**Issue by dunk** [6si/shipwright#50]
It has taken me quite some time to get things working - this was on account of it not being obvious that you have to *commit your changes to git* before shipwright will build anything. This behaviour makes the dev cycle a bit annoying if you are rapidly iterating on a container and building it a lot. Any easy way to get shipwright to build, say, a "dev" build from the files in the directory without having to commit first?

**Comment by srobertson** [comment]
Hi Dukn, we're discussing a fix for that in #42
