### ISSUE TITLE
Feature Request: Ignore Directories List in .shipwright.json

### ISSUE THREAD

**Issue by kgpayne** [6si/shipwright#73]
I have a container for AWS DynamoDB local that is testing only (in prod I use the actual service). I'd prefer it didn't build and push every time, so would be great to exclude it from the build process. Thanks!

**Comment by graingert** [comment]
`shipwright push -x service3`

**Comment by kgpayne** [comment]
Amazing, thanks :)

**Comment by graingert** [comment]
I find it's better to whitelist with -u prod eg whataver
