### ISSUE TITLE
Fails on docker-mac due to incorrect docker version reported

### ISSUE THREAD

**Issue by cdomigan** [6si/shipwright#94]
Trying to run shipwright on Docker for Mac:

`/usr/local/lib/python2.7/site-packages/docker/api/client.py:151: UserWarning: The minimum API version supported is 1.21, but you are using version 1.18. It is recommended you either upgrade Docker Engine or use an older version of Docker SDK for Python.
  'Python.'.format(MINIMUM_DOCKER_API_VERSION, self._version)
Aborting build, due to uncommitted changes. If you are not ready to commit these changes, re-run with the --dirty flag.`

But running `docker version` shows:
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true`

---
The server API version is at 1.25 which should be supported

**Comment by graingert** [comment]
Read the full error message
```
'Python.'.format(MINIMUM_DOCKER_API_VERSION, self._version) Aborting build, due to uncommitted changes. If you are not ready to commit these changes, re-run with the --dirty flag.
```

**Comment by graingert** [comment]
See also: https://github.com/6si/shipwright/pull/74
